### ISSUE TITLE
SETR读取数据集trans10kv2出错

### ISSUE THREAD

**Issue by wstchhwp** [BR-IDL/PaddleViT#119]
同样都是trans10kv2， segformer可以训练完成，而SETR报了如下错误：

训练配置如下：
# 数据集的设置
DATA:
    BATCH_SIZE: 16  
    BATCH_SIZE_VAL: 16  
    DATASET: 'Trans10kV2'
    DATA_PATH: '/home/xxxxxxxx/dataset/Trans10K_cls12'
    CROP_SIZE: (224, 224) 
    NUM_CLASSES: 12

4张v100,8张v100都会训练出错。
感觉segformer可以训练完成，而setr迭代70个iters就会报一下错误！感觉好奇怪

Traceback (most recent call last):
  File "train.py", line 166, in <module>
main()
  File "train.py", line 113, in main
    loss.backward()
  File "/home/easyits/anaconda3/envs/paddle22/lib/python3.7/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/easyits/anaconda3/envs/paddle22/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/home/easyits/anaconda3/envs/paddle22/lib/python3.7/site-packages/paddle/fluid/framework.py", line 229, in __impl__
    return func(*args, **kwargs)
  File "/home/easyits/anaconda3/envs/paddle22/lib/python3.7/site-packages/paddle/fluid/dygraph/varbase_patch_methods.py", line 249, in backward
    framework._dygraph_tracer())
ValueError: (InvalidArgument) Input dimension size should be equal to 4, but received dimension size is 3.
  [Hint: Expected arity(dims) == D, but received arity(dims):4 != D:3.] (at /paddle/paddle/fluid/framework/eigen.h:35)

**Comment by xperzy** [comment]
Thanks for the issue.    @ToscanaGoGithub @wutianyiRosun  Could you help handle this issue?

**Comment by wstchhwp** [comment]
> Thanks for the issue. @ToscanaGoGithub @wutianyiRosun Could you help handle this issue?

我试了单张v100训练没有任何问题，因为SETR模型参数比较大，在多卡训练的时候，并且num_workers=0，可能是多卡加载通信的原因吧
