### ISSUE TITLE
t2t利用paddlelite进行pto可以导出定点模型，但评测时报错

### ISSUE THREAD

**Issue by GtxMiracle** [BR-IDL/PaddleViT#214]
Traceback (most recent call last):
  File "eval.py", line 120, in <module>
    main()
  File "eval.py", line 116, in main
    eval(args)
  File "eval.py", line 80, in eval
    fetch_list=fetch_targets)
  File "/Users/gtx/opt/anaconda3/envs/paddle/lib/python3.6/site-packages/paddle/fluid/executor.py", line 1262, in run
    six.reraise(*sys.exc_info())
  File "/Users/gtx/opt/anaconda3/envs/paddle/lib/python3.6/site-packages/six.py", line 719, in reraise
    raise value
  File "/Users/gtx/opt/anaconda3/envs/paddle/lib/python3.6/site-packages/paddle/fluid/executor.py", line 1260, in run
    return_merged=return_merged)
  File "/Users/gtx/opt/anaconda3/envs/paddle/lib/python3.6/site-packages/paddle/fluid/executor.py", line 1402, in _run_impl
    use_program_cache=use_program_cache)
  File "/Users/gtx/opt/anaconda3/envs/paddle/lib/python3.6/site-packages/paddle/fluid/executor.py", line 1492, in _run_program
    [fetch_var_name])
RuntimeError: (PreconditionNotMet) The number of first scale values must be the same with corresponding dimension value of Input(X) when the `Scales` has two elements, but 64 != 3136 here.
  [Hint: Expected scales[0]->numel() == in->dims()[x_num_col_dims], but received scales[0]->numel():64 != in->dims()[x_num_col_dims]:32.] (at /home/Paddle/paddle/fluid/operators/fake_dequantize_op.h:90)
  [operator < fake_channel_wise_dequantize_max_abs > error]

浮点inference模型使用如下方式导出：
from config import get_config
from t2t_vit import build_t2t_vit as build_model
import paddle
from paddle.static import InputSpec

# config files in ./configs/
config = get_config('./configs/t2t_vit_7.yaml')
# build model
model = build_model(config)
# load pretrained weights
model_state_dict = paddle.load('./t2t_vit_7.pdparams')
model.set_state_dict(model_state_dict)
model.eval()
# net = paddle.jit.to_static(model)
# data = paddle.rand((1,3, 224, 224))
# out = net(data)
x_spec = InputSpec(shape=[None, 3, 224, 224], dtype='float32', name='x')
model = paddle.jit.save(model, './t2t', input_spec=[x_spec])
量化和评测均使用官方提供demo：https://github.com/PaddlePaddle/PaddleSlim/tree/develop/demo/quant/quant_post

**Comment by xperzy** [comment]
Thanks for the issue, I'm fixing this problem and will update once finished.

**Comment by xperzy** [comment]
Hello @GtxMiracle, I have fixed the code and now in my env the model after quant can be load and run using paddleslim eval.py.
  
Please check the new commit [here](https://github.com/BR-IDL/PaddleViT/commit/b1da9f33a851ddd89f32df08394d628ea64ce73f) 

and newly added documents [here](https://github.com/BR-IDL/PaddleViT/blob/develop/docs/paddlevit-quant-cn.md) for details.

**Comment by GtxMiracle** [comment]
您好，使用了您提供的最新的模型文件和导出脚本，量化后的模型测试时仍然报错：
Traceback (most recent call last):
  File "eval.py", line 120, in <module>
    main()
  File "eval.py", line 116, in main
    eval(args)
  File "eval.py", line 80, in eval
    fetch_list=fetch_targets)
  File "/Users/gtx/opt/anaconda3/envs/paddle/lib/python3.6/site-packages/paddle/fluid/executor.py", line 1262, in run
    six.reraise(*sys.exc_info())
  File "/Users/gtx/opt/anaconda3/envs/paddle/lib/python3.6/site-packages/six.py", line 719, in reraise
    raise value
  File "/Users/gtx/opt/anaconda3/envs/paddle/lib/python3.6/site-packages/paddle/fluid/executor.py", line 1260, in run
    return_merged=return_merged)
  File "/Users/gtx/opt/anaconda3/envs/paddle/lib/python3.6/site-packages/paddle/fluid/executor.py", line 1402, in _run_impl
    use_program_cache=use_program_cache)
  File "/Users/gtx/opt/anaconda3/envs/paddle/lib/python3.6/site-packages/paddle/fluid/executor.py", line 1492, in _run_program
    [fetch_var_name])
RuntimeError: (NotFound) Operator (fake_quantize_dequantize_moving_average_abs_max) does not have kernel for data_type[int]:data_layout[ANY_LAYOUT]:place[CPUPlace]:library_type[PLAIN].
  [Hint: Expected kernel_iter != kernels.end(), but received kernel_iter == kernels.end().] (at /home/Paddle/paddle/fluid/framework/operator.cc:1297)
  [operator < fake_quantize_dequantize_moving_average_abs_max > error]

**Comment by xperzy** [comment]
@GtxMiracle 模型导出方式是否按照上面提到的文档提供的方式进行导出？ 转静态图过程中有无报错？ batchsize等是否设置正确？

**Comment by xperzy** [comment]
请提供更多的信息，方便我们判断问题在哪。
